version: '3.7'

networks:
  app_subnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  docker_redis_sentinel_master:
    container_name: docker_redis_sentinel_master
    image: redis
    ports:
      - 6300:6379
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./docker_data/redis_sentinel_master:/data
      - ./docker_conf/redis_sentinel_master/redis_sentinel_master.conf:/usr/local/etc/redis/redis.conf
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      app_subnet:
        ipv4_address: 172.20.0.35
    restart: always

  docker_redis_sentinel_slave:
    container_name: docker_redis_sentinel_slave
    image: redis
    ports:
      - 6301:6379
    command: redis-server /usr/local/etc/redis/redis.conf --slaveof docker_redis_sentinel_master 6379
    volumes:
      - ./docker_data/redis_sentinel_slave:/data
      - ./docker_conf/redis_sentinel_slave/redis_sentinel_slave.conf:/usr/local/etc/redis/redis.conf
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      app_subnet:
        ipv4_address: 172.20.0.31
    depends_on:
      - docker_redis_sentinel_master
    restart: always

  docker_redis_sentinel_1:
    container_name: docker_redis_sentinel_1
    image: redis
    ports:
      - 26379:26379
    command: redis-sentinel /usr/local/etc/redis/redis_sentinel_1.conf
    volumes:
      - ./docker_data/redis_sentinel_1:/data 
      - ./docker_conf/redis_sentinel_1:/usr/local/etc/redis 
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      app_subnet:
        ipv4_address: 172.20.0.32
    depends_on:
      - docker_redis_sentinel_master
    restart: always

  docker_redis_sentinel_2:
    container_name: docker_redis_sentinel_2
    image: redis
    ports:
      - 26380:26380
    command: redis-sentinel /usr/local/etc/redis/redis_sentinel_2.conf
    volumes:
      - ./docker_data/redis_sentinel_2:/data
      - ./docker_conf/redis_sentinel_2:/usr/local/etc/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      app_subnet:
        ipv4_address: 172.20.0.33
    depends_on:
      - docker_redis_sentinel_master
    restart: always

  docker_redis_sentinel_3:
    container_name: docker_redis_sentinel_3
    image: redis
    ports:
      - 26381:26381
    command: redis-sentinel /usr/local/etc/redis/redis_sentinel_3.conf
    volumes:
      - ./docker_data/redis_sentinel_3:/data
      - ./docker_conf/redis_sentinel_3:/usr/local/etc/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      app_subnet:
        ipv4_address: 172.20.0.34
    depends_on:
      - docker_redis_sentinel_master
    restart: always


