spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/spring_jpa
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show_sql: true

logging.level:
  org.hibernate.SQL: debug