spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_jpa
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 10
      maxLifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: create
    show_sql: true
    defer-datasource-initialization: true

logging.level:
  org.hibernate.SQL: debug