server:
  port: 8080

redis:
  host: localhost
  port: 6379

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/spring_redis
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
