spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/spring_jdbc
      username: sa
      password:
      maximum-pool-size: 200

logging.level:
  org.hibernate.SQL: debug
